### ISSUE TITLE
Not able to download model weights

### ISSUE THREAD

**Issue by gessha** [dihuangdh/HHOR#1]
Hi authors,

I tried downloading the model checkpoints but I couldn't because they are restricted behind University of Sydney account restrictions. Could you make them available for download by anyone? One way to test this out is to try downloading them from an incognito browser window.

Edit: I was able to download the demo data but not the pretrained models. 

Thank you for your time,
Georgi

**Comment by dihuangdh** [comment]
Thanks, Georgi, I will fix this as soon as possible.

**Comment by dihuangdh** [comment]
Hi Georgi, I test the download link in 1) a Macbook 2) an incognito browser of a Macbook 3) an Ubuntu computer 4) an incognito browser Ubuntu computer.  All works fine for me. 

When I use the Macbook, the browser asks me to enter the USYD account, just like what happened to you. However, you can just ignore/close the login page and refresh the browser, then you are able to download the data and pretrained models.

**Comment by gessha** [comment]
I found the download the button. Sorry for the trouble!
