### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'pytorch_resnet101.pth'

### ISSUE THREAD

**Issue by anilesec** [dihuangdh/HHOR#2]
Dear @dihuangdh 

At the matting step, i get file not found error.

I changed the path of this checkpoint to "work_dirs/deeplabv3plus_r101-d8_512x512_160k_handseg3/latest.pth"

Is this correct? or should I need to download "pytorch_resnet101.pth" their github page and use it?

Thanks in Advance!

**Comment by dihuangdh** [comment]
Hi @anilesec ,

The Matting algorithm is adopted from [BackgroundMattingV2](https://github.com/PeterL1n/BackgroundMattingV2), you can follow their installation steps and download their models [HERE](https://drive.google.com/drive/folders/1cbetlrKREitIgjnIikG1HdM4x72FtgBh).

Best,
Di
