### ISSUE TITLE
Some question about the dataset

### ISSUE THREAD

**Issue by EAST-J** [dihuangdh/HHOR#6]
Hi, I have some confusion about the dataset and evaluation.
1. What the unit of the GT object CAD model?
2. Did you use the post-processing when evaluate the CD value?

**Comment by Siwensun** [comment]
Do you know where is the all 35 CAD models?

**Comment by EAST-J** [comment]
> Do you know where is the all 35 CAD models?

No, it seems that only can get part CAD models.

**Comment by anilesec** [comment]
@EAST-J  If you are looking for a similar dataset with CAD models for both object and hand-object. Here is one:
https://europe.naverlabs.com/research/showme/ (contact authors if you need more information)
